version: "3.9"
services:
  mysql-service:
    restart: unless-stopped
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_DATABASE: fintracker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    